Models/Burger.cs
using BanterBurger.Models;

namespace BanterBurger.Models
{
	public class Burger
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public decimal Price { get; set; }
		public String Bun { get; set; }
		public string Patty { get; set; }
		public String Condiments { get; set; }


    }



}

Models/BurgerFactory.cs
namespace BanterBurger.Models
{
	public class BurgerFactory : iBurger
	{
		public Burger CreateBurger(string type)
		{
			switch (type.ToLower())
			{
				case "plain":
					return new Burger { Id = 1, Name = "Plain Burger", Price = 4.99m, Bun = "Wheat", Patty = "Beef", Condiments = "Mayo" };
				case "cheese":
					return new Burger { Id = 2, Name = "Cheese Burger", Price = 7.99m, Bun = "Wheat", Patty = "Beef", Condiments = "Cheese Sauce" };
				case "veggie":
					return new Burger { Id = 3, Name = "Veggie Burger", Price = 5.99m, Bun = "Wheat", Patty = "Lentils", Condiments = "Sweet Chillie" };
				case "chicken":
					return new Burger { Id = 4, Name = "Chicken Burger", Price = 9.99m, Bun = "Wheat", Patty = "Chicken", Condiments = "Chutney" };
				case "rib":
					return new Burger { Id = 5, Name = "Rib Burger", Price = 11.99m, Bun = "Wheat", Patty = "Beef Rib", Condiments = "Rib Sauce" };
				default:
					throw new ArgumentException("Invalid burger type");
			}
		}
	}
}

Models/ErrorViewModel.cs
namespace AnotherBanterBurger.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/iBurger.cs
namespace BanterBurger.Models
{
	public interface iBurger
	{
		Burger CreateBurger(string type);


	}

}

Controllers/BurgersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AnotherBanterBurger.Data;
using BanterBurger.Models;

namespace AnotherBanterBurger.Controllers
{
    public class BurgersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BurgersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Burgers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Burger.ToListAsync());
        }

        // GET: Burgers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var burger = await _context.Burger
                .FirstOrDefaultAsync(m => m.Id == id);
            if (burger == null)
            {
                return NotFound();
            }

            return View(burger);
        }

        // GET: Burgers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Burgers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Bun,Patty,Condiments")] Burger burger)
        {
            if (ModelState.IsValid)
            {
                _context.Add(burger);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(burger);
        }

        // GET: Burgers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var burger = await _context.Burger.FindAsync(id);
            if (burger == null)
            {
                return NotFound();
            }
            return View(burger);
        }

        // POST: Burgers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Bun,Patty,Condiments")] Burger burger)
        {
            if (id != burger.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(burger);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BurgerExists(burger.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(burger);
        }

        // GET: Burgers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var burger = await _context.Burger
                .FirstOrDefaultAsync(m => m.Id == id);
            if (burger == null)
            {
                return NotFound();
            }

            return View(burger);
        }

        // POST: Burgers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var burger = await _context.Burger.FindAsync(id);
            if (burger != null)
            {
                _context.Burger.Remove(burger);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BurgerExists(int id)
        {
            return _context.Burger.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using AnotherBanterBurger.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AnotherBanterBurger.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Burgers/Create.cshtml
@model BanterBurger.Models.Burger

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Burger</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bun" class="control-label"></label>
                <input asp-for="Bun" class="form-control" />
                <span asp-validation-for="Bun" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patty" class="control-label"></label>
                <input asp-for="Patty" class="form-control" />
                <span asp-validation-for="Patty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condiments" class="control-label"></label>
                <input asp-for="Condiments" class="form-control" />
                <span asp-validation-for="Condiments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Burgers/Delete.cshtml
@model BanterBurger.Models.Burger

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Burger</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bun)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bun)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Patty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Patty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Condiments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Condiments)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Burgers/Details.cshtml
@model BanterBurger.Models.Burger

@{
    ViewData["Title"] = "Details";
}

<h1 class="mb-4">Burger Details</h1>

<div class="container">
    <div class="row shadow rounded">
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
            <h3 class="fw-bold mb-3"> @Html.DisplayFor(model => model.Name) </h3>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bun)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bun)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Patty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Patty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Condiments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Condiments)
        </dd>
    </dl>
</div>
        <div class="col-sm-8 col-md-4 col-lg-2 col-xl-2">
            <img src="https://cdn.openart.ai/uploads/image_aX0_5_te_1710071546120_512.webp" alt="Beef Burger" height="200px">
        </div>
</div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Burgers/Edit.cshtml
@model BanterBurger.Models.Burger

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Burger</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bun" class="control-label"></label>
                <input asp-for="Bun" class="form-control" />
                <span asp-validation-for="Bun" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patty" class="control-label"></label>
                <input asp-for="Patty" class="form-control" />
                <span asp-validation-for="Patty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condiments" class="control-label"></label>
                <input asp-for="Condiments" class="form-control" />
                <span asp-validation-for="Condiments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Burgers/Index.cshtml
@model IEnumerable<BanterBurger.Models.Burger>

@{
    ViewData["Title"] = "Index";
}

<h1 class="fw-bold">Menu</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row shadow rounded">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bun)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Condiments)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bun)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Condiments)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row shadow rounded">
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
            <div id="carouselSlidesOnly" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000">
                <div class="carousel-inner h-100">
                    <div class="carousel-item active">
                        <img src="https://cdn.openart.ai/uploads/image_aX0_5_te_1710071546120_512.webp" class="d-block w-100" alt="Beef Burger">
                    </div>
                    <div class="carousel-item">
                        <img src="https://cdn.openart.ai/uploads/image_ze44gI8q_1710071985742_512.webp" class="d-block w-100" alt="Double Beef Burger">
                    </div>
                    <div class="carousel-item">
                        <img src="https://cdn.openart.ai/uploads/image_QVz0Rxbg_1710071399175_512.webp" class="d-block w-100" alt="Double Chicken Burger">
                    </div>
                    <div class="carousel-item">
                        <img src="https://cdn.openart.ai/uploads/image_KUBiR27M_1710071629924_512.webp" class="d-block w-100" alt="Vegetarian Burger">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselSlidesOnly" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselSlidesOnly" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
            <div class="mb-3">
                <h2>Where Every Bite is a Study Break!</h2>
            </div>
            <div class="mb-2 p-3">
                <span class="py-2 fw-bold">Quality, Quantity, and Quality Again!</span>
                <p class="py-2">Here at Banter Burger, we are committed to offering high-quality ingredients, generous portions, and consistently excellent service</p>
            </div>
            <div class="mb-2 p-3">
                <span class="py-2 fw-bold">Flavorful, Fast, and Friendly!</span>
                <p class="py-2">Here at Banter Burger, we are dedicated to making every visit a memorable one, with our flavorful burgers, fast service, and friendly staff.</p>
            </div>
            <div class="mb-2 p-3">
                <span class="py-2 fw-bold">Campus's Best-Kept Secret!</span>
                <p class="py-2">Here at Banter Burger, we are more than just a burger joint; we are your campus's best-kept secret, offering a unique and memorable dining experience.</p>
            </div>
            <div class="mb-2 p-3">
                <span class="py-2 fw-bold">Burger, Banter, and Brews: Where Students Meet!</span>
                <p class="py-2">Here at Banter Burger, we believe in the power of a great burger, a lively atmosphere, and the joy of meeting friends.</p>
            </div>
        </div>
    </div>
</div>

<div>
    <p>     </p>
    <p>     </p>
</div>

<div class="container">
    <div class="row shadow rounded">
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
            <div class="mb-3">
                <h2>Specials!</h2>
            </div>
            <div class="mb-2 p-3">
                <span class="py-2 fw-bold">Ultimate Beef Feast</span>
                <p class="py-2">Double-stacked beef burger, crispy on the outside and meltingly tender on the inside. Accompanied bycrispy fries. To wash it all down, a cold, frothy beer.</p>
            </div>
            <div class="mb-2 p-3">
                <span class="py-2 fw-bold">Gourmet Beef Burger Delight</span>
                <p class="py-2">Loaded Beef Burger, accompanied by a side of crispy, golden-fried fries, and two refreshing drinks</p>
            </div>
            <div class="mb-2 p-3">
                <span class="py-2 fw-bold">Grand Beef Burger</span>
                <p class="py-2">A sumptuous feast that includes a juicy beef burger, accompanied by two sides, and a drink that completes the meal with a delightful finish.</p>
            </div>
            <div class="mb-2 p-3">
                <span class="py-2 fw-bold">Student Meal</span>
                <p class="py-2">Anything you're willing to pay for.</p>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
            <div id="carouselSlidesOnly2" class="carousel slide" data-bs-ride="carousel" data-bs-interval="12000">
                <div class="carousel-inner h-100" ">
                    <div class="carousel-item active">
                        <img src="https://cdn.openart.ai/uploads/image_-oISPAQ1_1710072530782_512.webp" class="d-block w-100" alt="Double Beef Burger, Fries, and a Beer">
                    </div>
                    <div class="carousel-item">
                        <img src="https://cdn.openart.ai/uploads/image_JJ3KAybi_1710072582556_512.webp" class="d-block w-100" alt="Loaded Beef Burger, Fries, and 2 Drinks">
                    </div>
                    <div class="carousel-item">
                        <img src="https://cdn.openart.ai/uploads/image_7q9goO-O_1710072556397_512.webp" class="d-block w-100" alt="Beef Burger, 2 Sides, and a Drink">
                    </div>
                    <div class="carousel-item">
                        <img src="https://cdn.openart.ai/uploads/image_9gv35evE_1710072479997_512.webp" class="d-block w-100" alt="Student Meal">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselSlidesOnly2" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselSlidesOnly2" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</div>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        var myCarousel = document.querySelector('#carouselSlidesOnly')
        var carousel = new bootstrap.Carousel(myCarousel)
    });
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BanterBurger</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BanterBurger.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

</head>
<body>
    <header class="positon-sticky top-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bolder" asp-area="" asp-controller="Home" asp-action="Index">Banter Burger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Burgers" asp-action="">Menu</a>
                        </li>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top">
        <div class="container">
            <div class="row">
                <div class="mb-1 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                    <h5>Banter Burger</h5>
                    <p >Where Every Bite is a Study Break!</p>
                </div>
                <div class="mb-1 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                    <h5>Contact Us</h5>
                    <div class="mt-3">
                        <span class="fab fa-instagram"> Instagram</span>
                    </div>
                    <div class="mt-3">
                        <span class="fab fa-whatsapp"> WhatsApp</span>
                    </div>
                    <div class="mt-3">
                        <span class="fab fa-facebook"> Facebook</span>
                    </div>
                </div>
                <div class="mb-1 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                    <h5>Location</h5>
                    <p>5 Think Way</p>
                    <p>Idea Park</p>
                    <p>Delusional Town</p>
                    <p>6092</p>
                </div>
            </div>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>